name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get -y install cmake clang-8 clang++-8 g++ flex bison llvm-8 llvm-8-dev ninja-build
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_C_COMPILER=clang-8 -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_BUILD_TYPE=Debug -GNinja ..
        ninja
        ./shapes_tests
