name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-gcc:
    runs-on:
      - ubuntu-20.04
      - ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get -y install cmake g++ flex bison llvm-10 llvm-10-dev ninja-build
    - name: Build
      run: |
        cmake -S . -B build/ -Werror=dev -DCMAKE_BUILD_TYPE=Debug -GNinja
        ninja -C build/
        build/shapes_tests
  build-clang:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get -y install clang clang++ cmake flex bison llvm-10 llvm-10-dev ninja-build
    - name: Build
      run: |
        cmake -S . -B build/ -Werror=dev -DCMAKE_BUILD_TYPE=Debug -GNinja
        ninja -C build/
        build/shapes_tests
