name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04 ]
        compiler: [ {cpp: g++, c: gcc}, {cpp: clang++, c: clang} ]
        llvm: [ 10, 11, 12, 13 ]
    name: ${{ matrix.os }}, ${{ matrix.compiler.c }}, LLVM ${{ matrix.llvm }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get -y install cmake ${{ matrix.compiler.c }} ${{ matrix.compiler.cpp }} flex bison llvm-${{ matrix.llvm }}-dev ninja-build
    - name: Build
      run: |
        cmake -S . -B build/ -Werror=dev -DCMAKE_BUILD_TYPE=Debug -GNinja
        cmake --build build/
        build/shapes_tests
